[build]
base = "./"
publish = "build/"
command = "yarn build"

[dev]
framework = "#custom"
command = "yarn start-express-dev"
targetPort = 3_000
port = 8_443

[[redirects]]
from = "/*"
to = "/"
status = 200
